
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 26 18:02:59 CET 2013
//----------------------------------------------------

package jpslab.ast.parser;

/** CUP generated interface containing symbol constants. */
public interface CupSym {
  /* terminals */
  public static final int FORALL = 38;
  public static final int GROUP_AS = 31;
  public static final int DIVIDE = 12;
  public static final int STRING_LITERAL = 7;
  public static final int MORE_OR_EQUAL = 26;
  public static final int EQUALS = 15;
  public static final int XOR = 24;
  public static final int MINUS_FUNCTION = 35;
  public static final int FORANY = 39;
  public static final int LESS = 25;
  public static final int MINUS = 10;
  public static final int WHERE = 36;
  public static final int BOOLEAN_LITERAL = 6;
  public static final int NOT = 30;
  public static final int AND = 23;
  public static final int LESS_OR_EQUAL = 27;
  public static final int IN = 33;
  public static final int OR = 22;
  public static final int COMMA = 42;
  public static final int BAG = 40;
  public static final int PLUS = 9;
  public static final int MULTIPLY = 11;
  public static final int MIN = 28;
  public static final int DOT = 43;
  public static final int LEFT_ROUND_BRACKET = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MODULO = 13;
  public static final int JOIN = 37;
  public static final int UNIQUE = 17;
  public static final int AVG = 20;
  public static final int UNION = 18;
  public static final int NOT_EQUALS = 16;
  public static final int SUM = 19;
  public static final int DOUBLE_LITERAL = 5;
  public static final int COUNT = 21;
  public static final int INTERSECT = 34;
  public static final int AS = 32;
  public static final int STRUCT = 41;
  public static final int MAX = 29;
  public static final int MORE = 14;
  public static final int RIGHT_ROUND_BRACKET = 3;
  public static final int INTEGER_LITERAL = 4;
  public static final int IDENTIFIER = 8;
}

